# fly.toml app configuration file generated for streaming-catelogs on 2023-09-10T15:36:53+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "streaming-catelogs"
primary_region = "phx"

[build]

[http_service]
  internal_port = 9000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
